/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118350-ge20ee9f9ae-20250124"
#endif /* AVUTIL_FFVERSION_H */
